included:
  - Sources
  - Tests
excluded:
  - .build
opt_in_rules: [all]
disabled_rules:
  - anonymous_argument_in_multiline_closure
  - conditional_returns_on_newline
  - contrasted_opening_brace
  - discouraged_optional_collection
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - file_header
  - file_name
  - file_types_order
  - force_try
  - force_unwrapping
  - function_default_parameter_at_end
  - indentation_width
  - lower_acl_than_parent
  - missing_docs
  - no_extension_access_modifier
  - no_grouping_extension
  - no_magic_numbers
  - non_overridable_class_declaration
  - object_literal
  - prefer_nimble
  - prefixed_toplevel_constant
  - prohibited_interface_builder
  - required_deinit
  - sorted_enum_cases
  - static_over_final_class
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_on_newline
  - unowned_variable_capture
  - unused_optional_binding
  - unused_parameter
  - vertical_whitespace_between_cases
line_length:
  warning: 180
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
file_length:
  ignore_comment_only_lines: true
attributes:
  always_on_same_line:
    - '@IBAction'
    - '@NSManaged'
    - '@objc'
cyclomatic_complexity:
  ignores_case_statements: true
identifier_name:
  excluded:
    - ^i$
    - ^id$
multiline_arguments:
  only_enforce_after_first_closure_on_first_line: true
nesting:
  type_level: 2
number_separator:
  minimum_length: 5
trailing_comma:
  mandatory_comma: true
trailing_closure:
  only_single_muted_parameter: true
