name: CI-test

on: 
  push:
    branches: 
      - master
      - hotfix
  pull_request:
    branches: 
      - master
      - hotfix

jobs:
  spm:
    name: Test SPM Integration
    runs-on: macOS-latest
    needs: [macOS]
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v1
      - name: SPM test
        run: swift test
  macOS:
    name: Test on macOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v1
      - name: test
        run: set -o pipefail && xcrun xcodebuild test -scheme MultipartFormDataSwiftKit -destination "platform=macOS" clean test | xcpretty
  iOS:
    name: Test on iOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=13.1,name=iPhone 11 Pro"] #, "OS=12.4,name=iPhone XS", "OS=11.4,name=iPhone X", "OS=10.3.1,name=iPhone SE"]
    steps:
      - uses: actions/checkout@v1            
      - name: iOS - ${{ matrix.destination }}
        run: set -o pipefail && xcrun xcodebuild -scheme MultipartFormDataSwiftKit -destination "${{ matrix.destination }}" clean test | xcpretty
  tvOS:
    name: Test on tvOS 
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=13.0,name=Apple TV 4K"] #, "OS=11.4,name=Apple TV 4K", "OS=10.2,name=Apple TV 1080p"]
    steps:
      - uses: actions/checkout@v1            
      - name: tvOS - ${{ matrix.destination }}
        run: set -o pipefail && xcrun xcodebuild -scheme "MultipartFormDataSwiftKit" -destination "${{ matrix.destination }}" clean test | xcpretty
  watchOS:
    name: Test on watchOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=6.0,name=Apple Watch Series 5 - 44mm"] #, "OS=4.2,name=Apple Watch Series 3 - 42mm", "OS=3.2,name=Apple Watch Series 2 - 42mm"]
    steps:
      - uses: actions/checkout@v1
      - name: watchOS - ${{ matrix.destination }}
        run: set -o pipefail && xcrun xcodebuild -scheme "MultipartFormDataSwiftKit" -destination "${{ matrix.destination }}" clean build | xcpretty
