name: CI-test

on: 
  push:
    branches: 
      - master
      - hotfix
  pull_request:
    branches: 
      - master
      - hotfix

jobs:
  spm:
    name: Test SPM Integration
    runs-on: macOS-latest
    needs: [macOS]
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v1
      - name: SPM test
        run: swift test
  macOS:
    name: Test on macOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v1
      - name: macOS
        run: set -o pipefail && xcrun xcodebuild test -scheme MultipartFormDataSwiftKit -destination "platform=macOS" clean test | xcpretty
  iOS:
    name: Test on iOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=13.2,name=iPhone 11 Pro"]
    steps:
      - uses: actions/checkout@v1            
      - name: iOS - ${{ matrix.destination }}
        run: set -o pipefail && xcrun xcodebuild -scheme MultipartFormDataSwiftKit -destination "${{ matrix.destination }}" clean test | xcpretty
  tvOS:
    name: Test on tvOS 
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=13.2,name=Apple TV 4K"]
    steps:
      - uses: actions/checkout@v1            
      - name: tvOS - ${{ matrix.destination }}
        run: set -o pipefail && xcrun xcodebuild -scheme "MultipartFormDataSwiftKit" -destination "${{ matrix.destination }}" clean test | xcpretty
  # watchOS:
  #   name: Test on watchOS
  #   runs-on: macOS-latest
  #   env:
  #     DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
  #   strategy:
  #     matrix:
  #       destination: ["OS=6.1,name=Apple Watch Series 5 - 44mm"]
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: watchOS - ${{ matrix.destination }}
  #       run: set -o pipefail && xcrun xcodebuild -scheme "MultipartFormDataSwiftKit" -destination "${{ matrix.destination }}" clean build | xcpretty
