name: Danger
on:
  pull_request:
    types: [opened, synchronize, edited]
    branches: 
      - main
      - hotfix
jobs:
  danger:
    name: Danger
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref }}-${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Danger
        uses: 417-72KI/danger-swiftlint@cede6b054f0974088af775b7843437f4b14dc33e # v6.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
