name: Danger
on:
  pull_request:
    types: [opened, synchronize, edited]
    branches: 
      - main
      - hotfix
jobs:
  danger:
    name: Danger
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref }}-${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Danger
        uses: 417-72KI/danger-swiftlint@43b6256431e50e838b15f0ade42669db00308b0f # v6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
