name: Generate Xcodeproj
on:
  push:
    branches: 
      - generate-xcodeproj
    paths-ignore:
      - '*.xcodeproj'
jobs:
  generate:
    name: Generate Xcodeproj
    runs-on: macos-11
    strategy:
      matrix:
        xcode: [12.5]
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            .build
          key: ${{ runner.os }}-xcode${{ matrix.xcode }}-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-xcode${{ matrix.xcode }}-
      - name: Generate Xcodeproj
        run: swift package generate-xcodeproj
      - name: commit and push
        run: |
          git config advice.addIgnoredFile false
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f *.xcodeproj/project.pbxproj
          git commit -m 'Update xcodeproj'
          git push origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
