name: Post release
on:
  push: 
    tags: '*'
jobs:
  revert-release-mode:
    name: Switch release flag to false
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref }}-${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Switch release flag to false
        run: sed -i -r 's/(let isRelease = )(true|false)/\1false/g' Package.swift
      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m 'switch release flag to false' Package.swift
          git push origin