name: Release
on:
  push:
    branches: 
      - release/*
    paths-ignore:
      - '*.xcodeproj'
jobs:
  prepare:
    name: Prepare
    runs-on: macos-11
    strategy:
      matrix:
        xcode: [12.5.1]
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            .build
          key: ${{ runner.os }}-xcode${{ matrix.xcode }}-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-xcode${{ matrix.xcode }}-
      - run: scripts/release.sh
