name: Release
on:
  push:
    branches: 
      - release/*
    paths-ignore:
      - '*.xcodeproj'
jobs:
  prepare:
    name: Prepare
    runs-on: macos-11
    concurrency:
      group: ${{ github.head_ref }}-${{ github.workflow }}
      cancel-in-progress: true
    strategy:
      matrix:
        xcode: ['13.2.1']
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            .build
          key: ${{ runner.os }}-xcode${{ matrix.xcode }}-${{ hashFiles('Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-xcode${{ matrix.xcode }}-
      - run: scripts/release.sh
