name: Test
on:
  push:
    branches: 
      - master
      - hotfix
  pull_request:
    branches: 
      - master
      - hotfix
jobs:
  test:
    name: test
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: [11.6, 12]
        destination: 
          - "platform=macOS"
          - "platform=iOS Simulator,name=iPhone 11 Pro"
          - "platform=tvOS Simulator,name=Apple TV 4K"
          # - "platform=watchOS Simulator,name=Apple Watch Series 5 - 44mm"
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: | 
          set -o pipefail && \
          rm -rf 'MultipartFormDataParser.xcodeproj' && \
          xcrun xcodebuild -enableCodeCoverage YES -scheme MultipartFormDataParser -destination "${{ matrix.destination }}" clean test | xcpretty
