name: Test
on:
  push:
    branches: 
      - main
      - hotfix
    paths:
      - .github/workflows/test.yml
      - Package.*
      - Sources/**/*.swift
      - Tests/**/*.swift
  pull_request:
    paths:
      - .github/workflows/test.yml
      - Package.*
      - Sources/**/*.swift
      - Tests/**/*.swift
jobs:
  test:
    name: Test
    runs-on: macos-latest
    concurrency: 
      group: ${{ github.head_ref }}-${{ github.workflow }}-${{ matrix.xcode }}-${{ matrix.destination }}
      cancel-in-progress: true
    strategy:
      matrix:
        xcode: ['13.2.1']
        destination: 
          - "platform=macOS"
          - "platform=macOS,variant=Mac Catalyst"
          - "platform=iOS Simulator,name=iPhone 12 Pro"
          - "platform=tvOS Simulator,name=Apple TV 4K"
      fail-fast: false
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v3
      - id: create-destination-key
        name: Create destination key for cache
        run: echo "::set-output name=destination_key::$(echo "${{ matrix.destination }}" | sed -r 's/[, ]/_/g')"
      - uses: actions/cache@v3
        with:
          path: |
            .build/SourcePackages/checkouts
          key: ${{ runner.os }}-xcode-${{ matrix.xcode }}-${{ steps.create-destination-key.outputs.destination_key }}-${{ hashFiles('Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-xcode-${{ matrix.xcode }}-${{ steps.create-destination-key.outputs.destination_key }}-
      - name: test
        run: |
          defaults write com.apple.dt.XCBuild EnableSwiftBuildSystemIntegration 1
          set -o pipefail && \
          rm -rf 'MultipartFormDataParser.xcodeproj' && \
          xcrun xcodebuild \
          -enableCodeCoverage YES \
          -scheme MultipartFormDataParser \
          -destination "${{ matrix.destination }}" \
          -derivedDataPath '.build' \
          -resultBundlePath 'test_output/TestResult.xcresult' \
          clean test | xcpretty
      - name: Upload test result
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: ${{ steps.create-destination-key.outputs.destination_key }}
          path: test_output
          if-no-files-found: error
          retention-days: 7
  xcodebuild_result:
    name: Export xcodebuild test result
    needs: test
    runs-on: macOS-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: test_output
      - name: Merge xcresult files
        run:
          xcrun xcresulttool merge test_output/**/*.xcresult --output-path test_output/TestResults.xcresult
      - uses: kishikawakatsumi/xcresulttool@v1
        if: success() || failure()
        with:
          path: test_output/TestResults.xcresult
          show-passed-tests: false
          show-code-coverage: false
          upload-bundles: false

