name: Test
on:
  push:
    branches: 
      - main
      - hotfix
  pull_request:
    branches: 
      - main
      - hotfix
jobs:
  catalina:
    name: Catalina
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode: [11.7, 12]
        destination: 
          - "platform=macOS"
          - "platform=macOS,variant=Mac Catalyst"
          - "platform=iOS Simulator,name=iPhone 11 Pro"
          - "platform=tvOS Simulator,name=Apple TV 4K"
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            .build
          key: ${{ runner.os }}-xcode${{ matrix.xcode }}-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-xcode${{ matrix.xcode }}-
      - name: test
        run: | 
          set -o pipefail && \
          rm -rf 'MultipartFormDataParser.xcodeproj' && \
          xcrun xcodebuild -enableCodeCoverage YES -scheme MultipartFormDataParser -destination "${{ matrix.destination }}" clean test | xcpretty
  big_sur:
    name: Big Sur
    runs-on: macos-11
    strategy:
      matrix:
        xcode: [12.5]
        destination: 
          - "platform=macOS"
          - "platform=macOS,variant=Mac Catalyst"
          - "platform=iOS Simulator,name=iPhone 12 Pro"
          - "platform=tvOS Simulator,name=Apple TV 4K"
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            .build
          key: ${{ runner.os }}-xcode${{ matrix.xcode }}-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-xcode${{ matrix.xcode }}-
      - name: test
        run: | 
          set -o pipefail && \
          rm -rf 'MultipartFormDataParser.xcodeproj' && \
          xcrun xcodebuild -enableCodeCoverage YES -scheme MultipartFormDataParser -destination "${{ matrix.destination }}" clean test | xcpretty
