name: Test
on:
  push:
    branches: 
      - master
      - hotfix
  pull_request:
    branches: 
      - master
      - hotfix
env:
  DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer
jobs:
  macOS:
    name: macOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: test
        run: set -o pipefail && rm -rf 'MultipartFormDataParser.xcodeproj' && xcrun xcodebuild -enableCodeCoverage YES -scheme MultipartFormDataParser -destination "platform=macOS" clean test | xcpretty
  iOS:
    name: iOS
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ["iPhone 11 Pro"]
    steps:
      - uses: actions/checkout@v1            
      - name: test
        run: set -o pipefail && rm -rf 'MultipartFormDataParser.xcodeproj' && xcrun xcodebuild -enableCodeCoverage YES -scheme MultipartFormDataParser -destination "name=${{ matrix.destination }}" clean test | xcpretty
  tvOS:
    name: tvOS 
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ["Apple TV 4K"]
    steps:
      - uses: actions/checkout@v1            
      - name: test
        run: set -o pipefail && rm -rf 'MultipartFormDataParser.xcodeproj' && xcrun xcodebuild -enableCodeCoverage YES -scheme "MultipartFormDataParser" -destination "name=${{ matrix.destination }}" clean test | xcpretty
  # watchOS:
  #   name: watchOS
  #   runs-on: macOS-latest
  #   strategy:
  #     matrix:
  #       destination: ["OS=6.1,name=Apple Watch Series 5 - 44mm"]
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: watchOS - ${{ matrix.destination }}
  #       run: set -o pipefail && rm -rf 'MultipartFormDataParser.xcodeproj' && xcrun xcodebuild -enableCodeCoverage YES -scheme "MultipartFormDataParser" -destination "${{ matrix.destination }}" clean build | xcpretty
