name: Test
on:
  push:
    branches: 
      - main
      - hotfix
    paths:
      - .github/workflows/test.yml
      - Package.*
      - Sources/**/*.swift
      - Tests/**/*.swift
  pull_request:
    branches: 
      - main
      - hotfix
    paths:
      - .github/workflows/test.yml
      - Package.*
      - Sources/**/*.swift
      - Tests/**/*.swift
jobs:
  catalina:
    name: Catalina
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode: [11.7, 12]
        destination: 
          - "platform=macOS"
          - "platform=macOS,variant=Mac Catalyst"
          - "platform=iOS Simulator,name=iPhone 11 Pro"
          - "platform=tvOS Simulator,name=Apple TV 4K"
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - id: create_destination_key
        name: Create destination key for cache
        run: echo "::set-output name=destination_key::$(echo "${{ matrix.destination }}" | sed -E 's/[, ]/_/g')"
      - uses: actions/cache@v2
        with:
          path: |
            .build/SourcePackages
          key: ${{ runner.os }}-xcode_${{ matrix.xcode }}-${{ steps.create_destination_key.outputs.destination_key }}-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-xcode_${{ matrix.xcode }}-${{ steps.create_destination_key.outputs.destination_key }}-
      - name: test
        run: | 
          set -o pipefail && \
          rm -rf 'MultipartFormDataParser.xcodeproj' && \
          xcrun xcodebuild \
          -enableCodeCoverage YES \
          -scheme MultipartFormDataParser \
          -destination "${{ matrix.destination }}" \
          -derivedDataPath '.build' \
          clean test | xcpretty
  big_sur:
    name: Big Sur
    runs-on: macos-11
    strategy:
      matrix:
        xcode: [12.5]
        destination: 
          - "platform=macOS"
          - "platform=macOS,variant=Mac Catalyst"
          - "platform=iOS Simulator,name=iPhone 12 Pro"
          - "platform=tvOS Simulator,name=Apple TV 4K"
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - id: create_destination_key
        name: Create destination key for cache
        run: echo "::set-output name=destination_key::$(echo "${{ matrix.destination }}" | sed -r 's/[, ]/_/g')"
      - uses: actions/cache@v2
        with:
          path: |
            .build/SourcePackages
          key: ${{ runner.os }}-xcode_${{ matrix.xcode }}-${{ steps.create_destination_key.outputs.destination_key }}-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-xcode_${{ matrix.xcode }}-${{ steps.create_destination_key.outputs.destination_key }}-
      - name: test
        run: | 
          set -o pipefail && \
          rm -rf 'MultipartFormDataParser.xcodeproj' && \
          xcrun xcodebuild \
          -enableCodeCoverage YES \
          -scheme MultipartFormDataParser \
          -destination "${{ matrix.destination }}" \
          -derivedDataPath '.build' \
          clean test | xcpretty
